### ISSUE TITLE
Error while running in local `Linux` environment.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio-demo-04-12-2022-finance-demo#2]
The issue was reported by @nullblockone in discord (@shamb0). It looks like connector did not get started:

Produce, consume works:

![image](https://user-images.githubusercontent.com/26554085/163589540-92f590e6-f0d7-44eb-a82c-7bacb11af76f.png)

![image](https://user-images.githubusercontent.com/26554085/163589567-576f8902-f10f-4e4d-9efe-2e91d870fe20.png)

But connector stuck in init:

```
fluvio connector list
 NAME            TYPE  VERSION  STATUS 
 gme-http-input  http  latest     Init 
```

Additional information can be found at:
* https://discord.com/channels/695712741381636168/695731077406392360/964086349030375454
* https://hackmd.io/@rrk/Byk_YtUV5

**Comment by simlay** [comment]
Closed in https://github.com/infinyon/fluvio-demo-04-12-2022-finance-demo/commit/3cc283b6c14a1678b684e9bf3845cc6815cb2416

**Comment by ajhunyady** [comment]
Resolution, start cluster with `fluvio cluster start`. Using `--local` is not supported with connectors published in Dockerhub.
